name: Runner Test

on:
  workflow_dispatch:
    inputs:
      USE_SELF_HOSTED_RUNNER:
        description: "Use Self-Hosted Runner"
        type: choice
        options:
          - "true"
          - "false"
        default: "false"
        required: true

      SELF_HOSTED_RUNNER_LABEL:
        description: "Self-Hosted Runner Label"
        type: string
        default: ""
        required: false

jobs:
  test-runner:
    name: test-runner

    runs-on: ${{ inputs.USE_SELF_HOSTED_RUNNER == 'true' && inputs.SELF_HOSTED_RUNNER_LABEL || 'ubuntu-latest' }}

    steps:
      - name: Display Runner Information
        shell: bash
        run: |
          echo "====================================="
          echo "Runner Information"
          echo "====================================="
          echo "Runner Name              : $RUNNER_NAME"
          echo "Runner OS                : $RUNNER_OS"
          echo "Runner Architecture      : $RUNNER_ARCH"
          echo "Use Self Hosted Runner   : ${{ inputs.USE_SELF_HOSTED_RUNNER }}"
          echo "Configured Runner Label  : ${{ inputs.SELF_HOSTED_RUNNER_LABEL }}"
          echo "Workspace                : $GITHUB_WORKSPACE"
          echo "====================================="
